<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCuNzmcy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCuNzmcy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCuNzmcy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCuNzmcy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCuNzmcy\App_KernelDevDebugContainer([
    'container.build_hash' => 'CuNzmcy',
    'container.build_id' => '4149db67',
    'container.build_time' => 1709282201,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCuNzmcy');
